

export default function Terrain({ nodes, materials }) {

    return (
        <>
            <group name="Circle_54" position={[0, 3.99, 0]} scale={1.27}>
                <mesh
                    name="Object_108"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_108.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle001_55"
                position={[3.3, 3.99, -1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_110"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_110.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle002_56"
                position={[1.1, 4.98, -1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_112"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_112.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle003_57"
                position={[-1.1, 4.98, -1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_114"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_114.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle004_58"
                position={[-2.2, 3.99, 0]}
                scale={1.27}
            >
                <mesh
                    name="Object_116"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_116.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle005_59" position={[-1.1, 3, 1.9]} scale={1.27}>
                <mesh
                    name="Object_118"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_118.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle006_60"
                position={[1.1, 3.99, 1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_120"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_120.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle007_61" position={[0, 3, 3.8]} scale={1.27}>
                <mesh
                    name="Object_122"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_122.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle008_62" position={[2.2, 2, 3.8]} scale={1.27}>
                <mesh
                    name="Object_124"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_124.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle009_63" position={[3.3, 3, 1.9]} scale={1.27}>
                <mesh
                    name="Object_126"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_126.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle010_64" position={[-3.3, 3, 1.9]} scale={1.27}>
                <mesh
                    name="Object_128"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_128.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle011_65" position={[2.2, 2.99, 0]} scale={1.27}>
                <mesh
                    name="Object_130"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_130.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle012_66" position={[4.4, 2.99, 0]} scale={1.27}>
                <mesh
                    name="Object_132"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_132.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle013_67"
                position={[5.5, 2.01, 1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_134"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_134.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle014_68" position={[6.6, 2.01, 0]} scale={1.27}>
                <mesh
                    name="Object_136"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_136.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle015_69"
                position={[5.5, 2.01, -1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_138"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_138.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle016_70"
                position={[4.4, 2.99, 3.8]}
                scale={1.27}
            >
                <mesh
                    name="Object_140"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_140.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle017_71"
                position={[3.3, 1.99, 5.7]}
                scale={1.27}
            >
                <mesh
                    name="Object_142"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_142.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle018_72"
                position={[1.1, 1.99, 5.7]}
                scale={1.27}
            >
                <mesh
                    name="Object_144"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_144.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle019_73"
                position={[-1.1, 1.99, 5.7]}
                scale={1.27}
            >
                <mesh
                    name="Object_146"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_146.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle020_74"
                position={[-2.19, 2, 3.8]}
                scale={1.27}
            >
                <mesh
                    name="Object_148"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_148.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle022_75"
                position={[1.1, 3.99, -1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_150"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_150.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle023_76"
                position={[0, 5.98, -3.8]}
                scale={1.27}
            >
                <mesh
                    name="Object_152"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_152.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle024_77"
                position={[5.5, 1.98, 5.7]}
                scale={1.27}
            >
                <mesh
                    name="Object_154"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_154.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle025_78"
                position={[2.2, 0.99, 7.6]}
                scale={1.27}
            >
                <mesh
                    name="Object_156"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_156.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle026_79"
                position={[-4.39, 1.98, 3.8]}
                scale={1.27}
            >
                <mesh
                    name="Object_158"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_158.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle028_80"
                position={[-2.2, 0.99, 7.6]}
                scale={1.27}
            >
                <mesh
                    name="Object_160"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_160.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle029_81" position={[0, 0.99, 7.6]} scale={1.27}>
                <mesh
                    name="Object_162"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_162.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle030_82"
                position={[-1.1, 0.99, 9.5]}
                scale={1.27}
            >
                <mesh
                    name="Object_164"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_164.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle031_83"
                position={[-3.3, 0.99, 9.5]}
                scale={1.27}
            >
                <mesh
                    name="Object_166"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_166.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle032_84"
                position={[-4.4, 0.99, 7.6]}
                scale={1.27}
            >
                <mesh
                    name="Object_168"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_168.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle033_85"
                position={[-5.5, 0.99, 5.7]}
                scale={1.27}
            >
                <mesh
                    name="Object_170"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_170.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle034_86"
                position={[-6.59, 0.99, 3.79]}
                scale={1.27}
            >
                <mesh
                    name="Object_172"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_172.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle035_87"
                position={[-5.5, 0.99, 1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_174"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_174.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle036_88"
                position={[-4.4, 0.99, 0]}
                scale={1.27}
            >
                <mesh
                    name="Object_176"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_176.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle037_89"
                position={[1.1, 0.99, 9.5]}
                scale={1.27}
            >
                <mesh
                    name="Object_178"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_178.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle038_90"
                position={[3.3, 0.99, 9.5]}
                scale={1.27}
            >
                <mesh
                    name="Object_180"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_180.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle039_91"
                position={[4.4, 0.99, 7.6]}
                scale={1.27}
            >
                <mesh
                    name="Object_182"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_182.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="Circle040_92" position={[4.4, 2, 3.8]} scale={1.27}>
                <mesh
                    name="Object_184"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_184.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle041_93"
                position={[6.6, 1.98, 3.8]}
                scale={1.27}
            >
                <mesh
                    name="Object_186"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_186.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle027_94"
                position={[-3.29, 1.99, 5.7]}
                scale={1.27}
            >
                <mesh
                    name="Object_188"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_188.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle042_95"
                position={[7.7, 0.99, 1.9]}
                scale={1.27}
            >
                <mesh
                    name="Object_190"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_190.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle043_96"
                position={[8.8, 0.99, 3.81]}
                scale={1.27}
            >
                <mesh
                    name="Object_192"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_192.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle044_97"
                position={[7.7, 0.99, 5.71]}
                scale={1.27}
            >
                <mesh
                    name="Object_194"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_194.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle021_98"
                position={[2.22, 5.98, -11.6]}
                scale={1.27}
            >
                <mesh
                    name="Object_196"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_196.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle045_99"
                position={[-9.96, 5.98, -1.95]}
                scale={1.27}
            >
                <mesh
                    name="Object_198"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_198.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle046_100"
                position={[-11.05, 5.98, -3.84]}
                scale={1.27}
            >
                <mesh
                    name="Object_200"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_200.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle047_101"
                position={[-12.12, 5.98, -1.98]}
                scale={1.27}
            >
                <mesh
                    name="Object_202"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_202.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle048_102"
                position={[-12.15, 5.98, 9.62]}
                scale={1.27}
            >
                <mesh
                    name="Object_204"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_204.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle049_103"
                position={[-11.06, 5.98, 7.66]}
                scale={1.27}
            >
                <mesh
                    name="Object_206"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_206.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle050_104"
                position={[-5.55, 5.98, -9.74]}
                scale={1.27}
            >
                <mesh
                    name="Object_208"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_208.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle051_105"
                position={[14.34, 5.98, -5.7]}
                scale={1.27}
            >
                <mesh
                    name="Object_210"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_210.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Circle052_106"
                position={[12.17, 5.98, -5.73]}
                scale={1.27}
            >
                <mesh
                    name="Object_212"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_212.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
        </>
    )
}