

export default function Trees({ nodes, materials }) {

    return (
        <>
            <group name="pine3_111" position={[-0.11, 5.97, -4.22]}>
                <mesh
                    name="Object_222"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_222.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2_112"
                position={[-0.43, 5.97, -3.37]}
                scale={0.82}
            >
                <mesh
                    name="Object_224"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_224.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1_113"
                position={[0.5, 5.96, -3.44]}
                scale={0.76}
            >
                <mesh
                    name="Object_226"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_226.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut_114"
                position={[3.71, 2.98, 4.27]}
                scale={0.77}
            >
                <mesh
                    name="Object_228"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_228.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3001_115" position={[1.26, 4.98, -2.52]}>
                <mesh
                    name="Object_230"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_230.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2001_116"
                position={[1.84, 4.97, -1.83]}
                scale={0.82}
            >
                <mesh
                    name="Object_232"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_232.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2002_117"
                position={[0.46, 4.97, -2.06]}
                scale={0.82}
            >
                <mesh
                    name="Object_234"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_234.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1001_118"
                position={[3.23, 3.98, -2.59]}
                scale={0.76}
            >
                <mesh
                    name="Object_236"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_236.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3002_119" position={[4.02, 3.98, -2.1]}>
                <mesh
                    name="Object_238"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_238.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1002_120"
                position={[2.56, 3.98, -1.63]}
                scale={0.76}
            >
                <mesh
                    name="Object_240"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_240.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1003_121"
                position={[3.54, 3.98, -1.23]}
                scale={0.76}
            >
                <mesh
                    name="Object_242"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_242.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2003_122"
                position={[3.23, 3.97, -1.86]}
                scale={0.82}
            >
                <mesh
                    name="Object_244"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_244.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2004_123"
                position={[5.18, 2.97, 3.55]}
                scale={0.82}
            >
                <mesh
                    name="Object_246"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_246.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3003_124" position={[4.72, 2.99, 2.97]}>
                <mesh
                    name="Object_248"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_248.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut001_125"
                position={[4.78, 1.97, 5.27]}
                scale={0.77}
            >
                <mesh
                    name="Object_250"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_250.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut002_126"
                position={[6.28, 1.97, 6.11]}
                scale={0.77}
            >
                <mesh
                    name="Object_252"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_252.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut003_127"
                position={[6.16, 1.97, 5.12]}
                scale={0.77}
            >
                <mesh
                    name="Object_254"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_254.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut004_128"
                position={[1.5, 0.97, 7.2]}
                scale={0.77}
            >
                <mesh
                    name="Object_256"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_256.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut005_129"
                position={[2.95, 0.97, 8.05]}
                scale={0.77}
            >
                <mesh
                    name="Object_258"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_258.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut006_130"
                position={[0.28, 1.98, 5.59]}
                scale={0.77}
            >
                <mesh
                    name="Object_260"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_260.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut007_131"
                position={[-2.53, 1.98, 5.25]}
                scale={0.77}
            >
                <mesh
                    name="Object_262"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_262.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1004_132"
                position={[-1.68, 1.98, 4.27]}
                scale={0.76}
            >
                <mesh
                    name="Object_264"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_264.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2005_133"
                position={[-1.52, 1.99, 3.48]}
                scale={0.82}
            >
                <mesh
                    name="Object_266"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_266.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2006_134"
                position={[-2.22, 1.99, 3.05]}
                scale={0.82}
            >
                <mesh
                    name="Object_268"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_268.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1005_135"
                position={[-2.38, 1.98, 3.87]}
                scale={0.76}
            >
                <mesh
                    name="Object_270"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_270.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1006_136"
                position={[-2.89, 1.99, 3.36]}
                scale={0.67}
            >
                <mesh
                    name="Object_272"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_272.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine0_cut008_137"
                position={[-3, 3.99, 0.43]}
                scale={0.77}
            >
                <mesh
                    name="Object_274"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_274.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3004_138" position={[2.11, 5.97, -12.02]}>
                <mesh
                    name="Object_276"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_276.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2007_139"
                position={[1.79, 5.97, -11.16]}
                scale={0.82}
            >
                <mesh
                    name="Object_278"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_278.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1007_140"
                position={[2.71, 5.96, -11.24]}
                scale={0.76}
            >
                <mesh
                    name="Object_280"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_280.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3005_141" position={[-10.07, 3.99, -2.37]}>
                <mesh
                    name="Object_282"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_282.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2008_142"
                position={[-10.39, 3.98, -1.51]}
                scale={0.82}
            >
                <mesh
                    name="Object_284"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_284.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3006_143" position={[-11.59, 4.94, -4.13]}>
                <mesh
                    name="Object_286"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_286.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1009_144"
                position={[-11.38, 4.92, -3.28]}
                scale={0.76}
            >
                <mesh
                    name="Object_288"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_288.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3007_145" position={[-12.23, 5.97, -2.4]}>
                <mesh
                    name="Object_290"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_290.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2010_146"
                position={[-12.55, 5.97, -1.54]}
                scale={0.82}
            >
                <mesh
                    name="Object_292"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_292.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1010_147"
                position={[-11.63, 5.96, -1.62]}
                scale={0.76}
            >
                <mesh
                    name="Object_294"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_294.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1008_148"
                position={[-10.68, 4.92, -4.34]}
                scale={0.76}
            >
                <mesh
                    name="Object_296"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_296.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3008_149" position={[-12.25, 3.99, 9.2]}>
                <mesh
                    name="Object_298"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_298.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2009_150"
                position={[-12.58, 3.98, 10.05]}
                scale={0.82}
            >
                <mesh
                    name="Object_300"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_300.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3009_151" position={[-11.6, 4.94, 7.37]}>
                <mesh
                    name="Object_302"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_302.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1011_152"
                position={[-11.39, 4.92, 8.22]}
                scale={0.76}
            >
                <mesh
                    name="Object_304"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_304.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1012_153"
                position={[-10.68, 4.92, 7.16]}
                scale={0.76}
            >
                <mesh
                    name="Object_306"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_306.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3010_154" position={[-5.66, 5.97, -10.16]}>
                <mesh
                    name="Object_308"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_308.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2011_155"
                position={[-5.98, 5.97, -9.31]}
                scale={0.82}
            >
                <mesh
                    name="Object_310"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_310.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1013_156"
                position={[-5.06, 5.96, -9.38]}
                scale={0.76}
            >
                <mesh
                    name="Object_312"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_312.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3011_157" position={[14.23, 3.99, -6.12]}>
                <mesh
                    name="Object_314"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_314.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2012_158"
                position={[13.91, 3.98, -5.27]}
                scale={0.82}
            >
                <mesh
                    name="Object_316"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_316.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group name="pine3012_159" position={[12.07, 5.97, -6.16]}>
                <mesh
                    name="Object_318"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_318.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine2013_160"
                position={[11.75, 5.97, -5.3]}
                scale={0.82}
            >
                <mesh
                    name="Object_320"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_320.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="pine1014_161"
                position={[12.67, 5.96, -5.38]}
                scale={0.76}
            >
                <mesh
                    name="Object_322"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_322.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Tree1_162"
                position={[2.19, 2.95, -0.01]}
                scale={[0.77, 1, 0.77]}
            >
                <mesh
                    name="Object_324"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_324.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Tree1001_163"
                position={[1.86, 1.96, 5.75]}
                scale={[0.77, 1, 0.77]}
            >
                <mesh
                    name="Object_326"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_326.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Tree1002_164"
                position={[5.77, 1.99, -2.27]}
                scale={[0.77, 1, 0.77]}
            >
                <mesh
                    name="Object_328"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_328.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
            <group
                name="Tree1003_165"
                position={[-2.55, 3.98, -0.73]}
                scale={[0.77, 1, 0.77]}
            >
                <mesh
                    name="Object_330"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_330.geometry}
                    material={materials.lpb_gradient}
                />
            </group>
        </>
    )
}