/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: LowPolyBoy (https://sketchfab.com/lowPolyBoy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/free-low-poly-game-assets-bbbfbeccfc9047b8b3f15b1c90061cdf
title: (FREE) Low Poly Game Assets
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function LowPolyWorld(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/lowpoly_world.glb");
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Crossbow001_40"
                position={[-1.1, 3.02, 5.6]}
                scale={0.21}
              >
                <mesh
                  name="Object_80"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_80.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Crossbow002_42"
                position={[3.3, 3.02, 5.6]}
                scale={0.21}
              >
                <mesh
                  name="Object_84"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_84.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Crossbow003_44"
                position={[6.6, 3.02, -0.2]}
                scale={0.21}
              >
                <mesh
                  name="Object_88"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_88.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Crossbow004_46"
                position={[-0.03, 5, -0.15]}
                scale={0.21}
              >
                <mesh
                  name="Object_92"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_92.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="fan_48" position={[4.35, 3.72, 4.96]}>
                <mesh
                  name="Object_96"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_96.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Cylinder_167"
                position={[-2.09, 3.37, 1.85]}
                rotation={[Math.PI / 2, 0, 0]}
              >
                <mesh
                  name="Object_334"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_334.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Plane_2" scale={90.62}>
                <mesh
                  name="Object_4"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_4.geometry}
                  material={materials["hex.001"]}
                />
              </group>
              <group name="BerrHouse_3" position={[-2, 3.99, 0.31]}>
                <mesh
                  name="Object_6"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_6.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Bridge_4" position={[2.14, 2.88, 3.78]}>
                <mesh
                  name="Object_8"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_8.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube002_5" position={[4.8, 1.97, 5.95]}>
                <mesh
                  name="Object_10"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_10.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube003_6" position={[6.47, 1.97, 3.16]}>
                <mesh
                  name="Object_12"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_12.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube004_7" position={[7, 1.97, 3.07]}>
                <mesh
                  name="Object_14"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_14.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube005_8" position={[5.01, 1.97, 2.29]}>
                <mesh
                  name="Object_16"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_16.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube006_9" position={[6.2, 1.97, 2]}>
                <mesh
                  name="Object_18"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_18.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube007_10" position={[5.95, 1.97, 0.01]}>
                <mesh
                  name="Object_20"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_20.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube008_11" position={[7.38, 1.97, -0.4]}>
                <mesh
                  name="Object_22"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_22.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube009_12" position={[4.85, 1.97, -2.33]}>
                <mesh
                  name="Object_24"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_24.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube010_13" position={[5.09, 1.97, -1.6]}>
                <mesh
                  name="Object_26"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_26.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube011_14" position={[5.88, 1.97, -1.42]}>
                <mesh
                  name="Object_28"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_28.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube012_15" position={[2.94, 1.97, 3.39]}>
                <mesh
                  name="Object_30"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_30.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube013_16" position={[2.44, 1.97, 3.07]}>
                <mesh
                  name="Object_32"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_32.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube014_17" position={[2.82, 1.97, 3.98]}>
                <mesh
                  name="Object_34"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_34.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube015_18" position={[1.49, 1.97, 4.3]}>
                <mesh
                  name="Object_36"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_36.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube016_19" position={[2.06, 1.97, 4.68]}>
                <mesh
                  name="Object_38"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_38.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube017_20" position={[-2.23, 1.97, 4.63]}>
                <mesh
                  name="Object_40"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_40.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube018_21" position={[-3.52, 1.97, 5.12]}>
                <mesh
                  name="Object_42"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_42.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube019_22" position={[-3.04, 1.97, 5.44]}>
                <mesh
                  name="Object_44"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_44.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube020_23" position={[-3.52, 1.97, 5.64]}>
                <mesh
                  name="Object_46"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_46.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube021_24" position={[1.56, 0.97, 7.67]}>
                <mesh
                  name="Object_48"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_48.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube022_25" position={[2.98, 0.97, 7.39]}>
                <mesh
                  name="Object_50"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_50.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube023_26" position={[2.57, 0.97, 8.36]}>
                <mesh
                  name="Object_52"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_52.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube024_27" position={[2.95, 2.97, -0.33]}>
                <mesh
                  name="Object_54"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_54.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube025_28" position={[2.91, 2.97, 0.26]}>
                <mesh
                  name="Object_56"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_56.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube026_29" position={[5.19, 2.97, -0.39]}>
                <mesh
                  name="Object_58"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_58.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube027_30" position={[4.57, 2.97, -0.82]}>
                <mesh
                  name="Object_60"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_60.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube028_31" position={[-0.94, 2.97, 1.1]}>
                <mesh
                  name="Object_62"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_62.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube029_32" position={[-0.43, 2.97, 1.43]}>
                <mesh
                  name="Object_64"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_64.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube030_33" position={[1.11, 4.97, -1.5]}>
                <mesh
                  name="Object_66"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_66.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube031_34" position={[-1.96, 4.97, -1.93]}>
                <mesh
                  name="Object_68"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_68.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube032_35" position={[-1.64, 4.97, -1.45]}>
                <mesh
                  name="Object_70"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_70.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Cube033_36" position={[-0.39, 4.97, -2.18]}>
                <mesh
                  name="Object_72"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_72.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Tower2_38" position={[3.92, 3, 1.7]}>
                <group name="cannon_37" position={[0, 1.3, -0.01]}>
                  <mesh
                    name="Object_76"
                    castShadow
                    receiveShadow
                    geometry={nodes.Object_76.geometry}
                    material={materials.lpb_gradient}
                  />
                </group>
                <mesh
                  name="Object_74"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_74.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Tower001_39" position={[-1.1, 2.02, 5.6]}>
                <mesh
                  name="Object_78"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_78.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Tower002_41" position={[3.3, 2.01, 5.6]}>
                <mesh
                  name="Object_82"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_82.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Tower003_43" position={[6.6, 2.02, -0.2]}>
                <mesh
                  name="Object_86"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_86.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Tower004_45" position={[-0.03, 3.99, -0.15]}>
                <mesh
                  name="Object_90"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_90.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="farmHouse_47" position={[4.38, 2.99, 4.24]}>
                <mesh
                  name="Object_94"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_94.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="GoldTower_49" position={[5.5, 1.99, 1.7]}>
                <mesh
                  name="Object_98"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_98.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="GoldTower001_50" position={[-1.1, 4.98, -2]}>
                <mesh
                  name="Object_100"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_100.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="house_01_51" position={[4.4, 2.99, 0]}>
                <mesh
                  name="Object_102"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_102.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="house_01001_52"
                position={[5.5, 1.99, 5.6]}
                scale={0.85}
              >
                <mesh
                  name="Object_104"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_104.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="house_01002_53"
                position={[2.2, 1.02, 7.6]}
                scale={0.85}
              >
                <mesh
                  name="Object_106"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_106.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle_54" position={[0, 3.99, 0]} scale={1.27}>
                <mesh
                  name="Object_108"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_108.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle001_55"
                position={[3.3, 3.99, -1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_110"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_110.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle002_56"
                position={[1.1, 4.98, -1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_112"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_112.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle003_57"
                position={[-1.1, 4.98, -1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_114"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_114.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle004_58"
                position={[-2.2, 3.99, 0]}
                scale={1.27}
              >
                <mesh
                  name="Object_116"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_116.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle005_59" position={[-1.1, 3, 1.9]} scale={1.27}>
                <mesh
                  name="Object_118"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_118.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle006_60"
                position={[1.1, 3.99, 1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_120"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_120.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle007_61" position={[0, 3, 3.8]} scale={1.27}>
                <mesh
                  name="Object_122"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_122.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle008_62" position={[2.2, 2, 3.8]} scale={1.27}>
                <mesh
                  name="Object_124"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_124.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle009_63" position={[3.3, 3, 1.9]} scale={1.27}>
                <mesh
                  name="Object_126"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_126.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle010_64" position={[-3.3, 3, 1.9]} scale={1.27}>
                <mesh
                  name="Object_128"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_128.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle011_65" position={[2.2, 2.99, 0]} scale={1.27}>
                <mesh
                  name="Object_130"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_130.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle012_66" position={[4.4, 2.99, 0]} scale={1.27}>
                <mesh
                  name="Object_132"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_132.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle013_67"
                position={[5.5, 2.01, 1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_134"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_134.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle014_68" position={[6.6, 2.01, 0]} scale={1.27}>
                <mesh
                  name="Object_136"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_136.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle015_69"
                position={[5.5, 2.01, -1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_138"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_138.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle016_70"
                position={[4.4, 2.99, 3.8]}
                scale={1.27}
              >
                <mesh
                  name="Object_140"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_140.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle017_71"
                position={[3.3, 1.99, 5.7]}
                scale={1.27}
              >
                <mesh
                  name="Object_142"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_142.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle018_72"
                position={[1.1, 1.99, 5.7]}
                scale={1.27}
              >
                <mesh
                  name="Object_144"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_144.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle019_73"
                position={[-1.1, 1.99, 5.7]}
                scale={1.27}
              >
                <mesh
                  name="Object_146"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_146.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle020_74"
                position={[-2.19, 2, 3.8]}
                scale={1.27}
              >
                <mesh
                  name="Object_148"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_148.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle022_75"
                position={[1.1, 3.99, -1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_150"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_150.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle023_76"
                position={[0, 5.98, -3.8]}
                scale={1.27}
              >
                <mesh
                  name="Object_152"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_152.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle024_77"
                position={[5.5, 1.98, 5.7]}
                scale={1.27}
              >
                <mesh
                  name="Object_154"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_154.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle025_78"
                position={[2.2, 0.99, 7.6]}
                scale={1.27}
              >
                <mesh
                  name="Object_156"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_156.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle026_79"
                position={[-4.39, 1.98, 3.8]}
                scale={1.27}
              >
                <mesh
                  name="Object_158"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_158.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle028_80"
                position={[-2.2, 0.99, 7.6]}
                scale={1.27}
              >
                <mesh
                  name="Object_160"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_160.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle029_81" position={[0, 0.99, 7.6]} scale={1.27}>
                <mesh
                  name="Object_162"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_162.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle030_82"
                position={[-1.1, 0.99, 9.5]}
                scale={1.27}
              >
                <mesh
                  name="Object_164"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_164.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle031_83"
                position={[-3.3, 0.99, 9.5]}
                scale={1.27}
              >
                <mesh
                  name="Object_166"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_166.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle032_84"
                position={[-4.4, 0.99, 7.6]}
                scale={1.27}
              >
                <mesh
                  name="Object_168"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_168.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle033_85"
                position={[-5.5, 0.99, 5.7]}
                scale={1.27}
              >
                <mesh
                  name="Object_170"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_170.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle034_86"
                position={[-6.59, 0.99, 3.79]}
                scale={1.27}
              >
                <mesh
                  name="Object_172"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_172.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle035_87"
                position={[-5.5, 0.99, 1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_174"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_174.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle036_88"
                position={[-4.4, 0.99, 0]}
                scale={1.27}
              >
                <mesh
                  name="Object_176"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_176.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle037_89"
                position={[1.1, 0.99, 9.5]}
                scale={1.27}
              >
                <mesh
                  name="Object_178"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_178.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle038_90"
                position={[3.3, 0.99, 9.5]}
                scale={1.27}
              >
                <mesh
                  name="Object_180"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_180.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle039_91"
                position={[4.4, 0.99, 7.6]}
                scale={1.27}
              >
                <mesh
                  name="Object_182"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_182.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="Circle040_92" position={[4.4, 2, 3.8]} scale={1.27}>
                <mesh
                  name="Object_184"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_184.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle041_93"
                position={[6.6, 1.98, 3.8]}
                scale={1.27}
              >
                <mesh
                  name="Object_186"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_186.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle027_94"
                position={[-3.29, 1.99, 5.7]}
                scale={1.27}
              >
                <mesh
                  name="Object_188"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_188.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle042_95"
                position={[7.7, 0.99, 1.9]}
                scale={1.27}
              >
                <mesh
                  name="Object_190"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_190.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle043_96"
                position={[8.8, 0.99, 3.81]}
                scale={1.27}
              >
                <mesh
                  name="Object_192"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_192.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle044_97"
                position={[7.7, 0.99, 5.71]}
                scale={1.27}
              >
                <mesh
                  name="Object_194"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_194.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle021_98"
                position={[2.22, 5.98, -11.6]}
                scale={1.27}
              >
                <mesh
                  name="Object_196"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_196.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle045_99"
                position={[-9.96, 5.98, -1.95]}
                scale={1.27}
              >
                <mesh
                  name="Object_198"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_198.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle046_100"
                position={[-11.05, 5.98, -3.84]}
                scale={1.27}
              >
                <mesh
                  name="Object_200"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_200.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle047_101"
                position={[-12.12, 5.98, -1.98]}
                scale={1.27}
              >
                <mesh
                  name="Object_202"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_202.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle048_102"
                position={[-12.15, 5.98, 9.62]}
                scale={1.27}
              >
                <mesh
                  name="Object_204"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_204.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle049_103"
                position={[-11.06, 5.98, 7.66]}
                scale={1.27}
              >
                <mesh
                  name="Object_206"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_206.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle050_104"
                position={[-5.55, 5.98, -9.74]}
                scale={1.27}
              >
                <mesh
                  name="Object_208"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_208.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle051_105"
                position={[14.34, 5.98, -5.7]}
                scale={1.27}
              >
                <mesh
                  name="Object_210"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_210.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Circle052_106"
                position={[12.17, 5.98, -5.73]}
                scale={1.27}
              >
                <mesh
                  name="Object_212"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_212.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="farmHouse001_107" position={[-0.37, 2.99, 3.73]}>
                <mesh
                  name="Object_214"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_214.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Tower2001_108"
                position={[2.98, 3.15, 2.1]}
                rotation={[0, Math.PI / 2, 0]}
              >
                <mesh
                  name="Object_216"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_216.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Tower2002_109"
                position={[0.8, 2.14, 5.52]}
                rotation={[0, 0.53, 0]}
              >
                <mesh
                  name="Object_218"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_218.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="th_110" position={[1, 3.99, 2]}>
                <mesh
                  name="Object_220"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_220.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3_111" position={[-0.11, 5.97, -4.22]}>
                <mesh
                  name="Object_222"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_222.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2_112"
                position={[-0.43, 5.97, -3.37]}
                scale={0.82}
              >
                <mesh
                  name="Object_224"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_224.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1_113"
                position={[0.5, 5.96, -3.44]}
                scale={0.76}
              >
                <mesh
                  name="Object_226"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_226.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut_114"
                position={[3.71, 2.98, 4.27]}
                scale={0.77}
              >
                <mesh
                  name="Object_228"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_228.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3001_115" position={[1.26, 4.98, -2.52]}>
                <mesh
                  name="Object_230"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_230.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2001_116"
                position={[1.84, 4.97, -1.83]}
                scale={0.82}
              >
                <mesh
                  name="Object_232"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_232.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2002_117"
                position={[0.46, 4.97, -2.06]}
                scale={0.82}
              >
                <mesh
                  name="Object_234"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_234.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1001_118"
                position={[3.23, 3.98, -2.59]}
                scale={0.76}
              >
                <mesh
                  name="Object_236"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_236.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3002_119" position={[4.02, 3.98, -2.1]}>
                <mesh
                  name="Object_238"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_238.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1002_120"
                position={[2.56, 3.98, -1.63]}
                scale={0.76}
              >
                <mesh
                  name="Object_240"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_240.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1003_121"
                position={[3.54, 3.98, -1.23]}
                scale={0.76}
              >
                <mesh
                  name="Object_242"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_242.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2003_122"
                position={[3.23, 3.97, -1.86]}
                scale={0.82}
              >
                <mesh
                  name="Object_244"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_244.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2004_123"
                position={[5.18, 2.97, 3.55]}
                scale={0.82}
              >
                <mesh
                  name="Object_246"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_246.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3003_124" position={[4.72, 2.99, 2.97]}>
                <mesh
                  name="Object_248"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_248.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut001_125"
                position={[4.78, 1.97, 5.27]}
                scale={0.77}
              >
                <mesh
                  name="Object_250"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_250.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut002_126"
                position={[6.28, 1.97, 6.11]}
                scale={0.77}
              >
                <mesh
                  name="Object_252"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_252.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut003_127"
                position={[6.16, 1.97, 5.12]}
                scale={0.77}
              >
                <mesh
                  name="Object_254"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_254.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut004_128"
                position={[1.5, 0.97, 7.2]}
                scale={0.77}
              >
                <mesh
                  name="Object_256"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_256.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut005_129"
                position={[2.95, 0.97, 8.05]}
                scale={0.77}
              >
                <mesh
                  name="Object_258"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_258.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut006_130"
                position={[0.28, 1.98, 5.59]}
                scale={0.77}
              >
                <mesh
                  name="Object_260"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_260.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut007_131"
                position={[-2.53, 1.98, 5.25]}
                scale={0.77}
              >
                <mesh
                  name="Object_262"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_262.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1004_132"
                position={[-1.68, 1.98, 4.27]}
                scale={0.76}
              >
                <mesh
                  name="Object_264"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_264.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2005_133"
                position={[-1.52, 1.99, 3.48]}
                scale={0.82}
              >
                <mesh
                  name="Object_266"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_266.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2006_134"
                position={[-2.22, 1.99, 3.05]}
                scale={0.82}
              >
                <mesh
                  name="Object_268"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_268.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1005_135"
                position={[-2.38, 1.98, 3.87]}
                scale={0.76}
              >
                <mesh
                  name="Object_270"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_270.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1006_136"
                position={[-2.89, 1.99, 3.36]}
                scale={0.67}
              >
                <mesh
                  name="Object_272"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_272.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine0_cut008_137"
                position={[-3, 3.99, 0.43]}
                scale={0.77}
              >
                <mesh
                  name="Object_274"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_274.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3004_138" position={[2.11, 5.97, -12.02]}>
                <mesh
                  name="Object_276"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_276.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2007_139"
                position={[1.79, 5.97, -11.16]}
                scale={0.82}
              >
                <mesh
                  name="Object_278"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_278.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1007_140"
                position={[2.71, 5.96, -11.24]}
                scale={0.76}
              >
                <mesh
                  name="Object_280"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_280.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3005_141" position={[-10.07, 3.99, -2.37]}>
                <mesh
                  name="Object_282"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_282.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2008_142"
                position={[-10.39, 3.98, -1.51]}
                scale={0.82}
              >
                <mesh
                  name="Object_284"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_284.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3006_143" position={[-11.59, 4.94, -4.13]}>
                <mesh
                  name="Object_286"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_286.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1009_144"
                position={[-11.38, 4.92, -3.28]}
                scale={0.76}
              >
                <mesh
                  name="Object_288"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_288.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3007_145" position={[-12.23, 5.97, -2.4]}>
                <mesh
                  name="Object_290"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_290.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2010_146"
                position={[-12.55, 5.97, -1.54]}
                scale={0.82}
              >
                <mesh
                  name="Object_292"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_292.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1010_147"
                position={[-11.63, 5.96, -1.62]}
                scale={0.76}
              >
                <mesh
                  name="Object_294"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_294.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1008_148"
                position={[-10.68, 4.92, -4.34]}
                scale={0.76}
              >
                <mesh
                  name="Object_296"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_296.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3008_149" position={[-12.25, 3.99, 9.2]}>
                <mesh
                  name="Object_298"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_298.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2009_150"
                position={[-12.58, 3.98, 10.05]}
                scale={0.82}
              >
                <mesh
                  name="Object_300"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_300.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3009_151" position={[-11.6, 4.94, 7.37]}>
                <mesh
                  name="Object_302"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_302.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1011_152"
                position={[-11.39, 4.92, 8.22]}
                scale={0.76}
              >
                <mesh
                  name="Object_304"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_304.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1012_153"
                position={[-10.68, 4.92, 7.16]}
                scale={0.76}
              >
                <mesh
                  name="Object_306"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_306.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3010_154" position={[-5.66, 5.97, -10.16]}>
                <mesh
                  name="Object_308"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_308.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2011_155"
                position={[-5.98, 5.97, -9.31]}
                scale={0.82}
              >
                <mesh
                  name="Object_310"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_310.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1013_156"
                position={[-5.06, 5.96, -9.38]}
                scale={0.76}
              >
                <mesh
                  name="Object_312"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_312.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3011_157" position={[14.23, 3.99, -6.12]}>
                <mesh
                  name="Object_314"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_314.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2012_158"
                position={[13.91, 3.98, -5.27]}
                scale={0.82}
              >
                <mesh
                  name="Object_316"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_316.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group name="pine3012_159" position={[12.07, 5.97, -6.16]}>
                <mesh
                  name="Object_318"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_318.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine2013_160"
                position={[11.75, 5.97, -5.3]}
                scale={0.82}
              >
                <mesh
                  name="Object_320"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_320.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="pine1014_161"
                position={[12.67, 5.96, -5.38]}
                scale={0.76}
              >
                <mesh
                  name="Object_322"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_322.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Tree1_162"
                position={[2.19, 2.95, -0.01]}
                scale={[0.77, 1, 0.77]}
              >
                <mesh
                  name="Object_324"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_324.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Tree1001_163"
                position={[1.86, 1.96, 5.75]}
                scale={[0.77, 1, 0.77]}
              >
                <mesh
                  name="Object_326"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_326.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Tree1002_164"
                position={[5.77, 1.99, -2.27]}
                scale={[0.77, 1, 0.77]}
              >
                <mesh
                  name="Object_328"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_328.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="Tree1003_165"
                position={[-2.55, 3.98, -0.73]}
                scale={[0.77, 1, 0.77]}
              >
                <mesh
                  name="Object_330"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_330.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
              <group
                name="WaterHouse_166"
                position={[-1.74, 2.99, 1.88]}
                rotation={[0, -Math.PI / 2, 0]}
              >
                <mesh
                  name="Object_332"
                  castShadow
                  receiveShadow
                  geometry={nodes.Object_332.geometry}
                  material={materials.lpb_gradient}
                />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/lowpoly_world.glb");


